char cfilename[200];
int *bufferVal;
float2 *chirp;
//char *dataIn;
float *dataOut;
float *tmp;
float2 *signal;
int site_id;
pthread_mutex_t file_mutex,stop_mutex;
struct runtime run_par;
struct argStruct arguments;
FILE *fpout;
float2 *gpuChirp; 
cufftHandle planf,planb;
char *tempIn;
//float2 *t_signal,*f_signal;
int *dev_nfft;
float *temp;
pthread_mutex_t data_mutex;
pthread_t acquire_thread;
int dataVal=0;
long double mjdnow();
long int pointer1=0;
